# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tarea2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tarea2.proto',
  package='tareaRPC',
  syntax='proto3',
  serialized_options=_b('\n\031io.grpc.examples.tareaRPCB\rTareaRPCProtoP\001\242\002\003RTG'),
  serialized_pb=_b('\n\x0ctarea2.proto\x12\x08tareaRPC\"\x18\n\x05Inbox\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\"\x17\n\x07Usuario\x12\x0c\n\x04name\x18\x01 \x01(\t\"B\n\x10\x44\x65stined_Message\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65stino\x18\x02 \x01(\t\x12\x0f\n\x07mensaje\x18\x03 \x01(\t\"\x1f\n\x0c\x43onfirmation\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb3\x02\n\x08TareaRPC\x12\x34\n\x0cRead_Message\x12\x11.tareaRPC.Usuario\x1a\x0f.tareaRPC.Inbox\"\x00\x12\x42\n\x13\x61\x63tualizar_usuarios\x12\x11.tareaRPC.Usuario\x1a\x16.tareaRPC.Confirmation\"\x00\x12\x44\n\x0cSend_Message\x12\x1a.tareaRPC.Destined_Message\x1a\x16.tareaRPC.Confirmation\"\x00\x12\x31\n\tSee_users\x12\x11.tareaRPC.Usuario\x1a\x0f.tareaRPC.Inbox\"\x00\x12\x34\n\x0cSee_messages\x12\x11.tareaRPC.Usuario\x1a\x0f.tareaRPC.Inbox\"\x00\x42\x32\n\x19io.grpc.examples.tareaRPCB\rTareaRPCProtoP\x01\xa2\x02\x03RTGb\x06proto3')
)




_INBOX = _descriptor.Descriptor(
  name='Inbox',
  full_name='tareaRPC.Inbox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='tareaRPC.Inbox.mensaje', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=50,
)


_USUARIO = _descriptor.Descriptor(
  name='Usuario',
  full_name='tareaRPC.Usuario',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tareaRPC.Usuario.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=75,
)


_DESTINED_MESSAGE = _descriptor.Descriptor(
  name='Destined_Message',
  full_name='tareaRPC.Destined_Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tareaRPC.Destined_Message.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destino', full_name='tareaRPC.Destined_Message.destino', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='tareaRPC.Destined_Message.mensaje', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=143,
)


_CONFIRMATION = _descriptor.Descriptor(
  name='Confirmation',
  full_name='tareaRPC.Confirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='tareaRPC.Confirmation.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=176,
)

DESCRIPTOR.message_types_by_name['Inbox'] = _INBOX
DESCRIPTOR.message_types_by_name['Usuario'] = _USUARIO
DESCRIPTOR.message_types_by_name['Destined_Message'] = _DESTINED_MESSAGE
DESCRIPTOR.message_types_by_name['Confirmation'] = _CONFIRMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Inbox = _reflection.GeneratedProtocolMessageType('Inbox', (_message.Message,), {
  'DESCRIPTOR' : _INBOX,
  '__module__' : 'tarea2_pb2'
  # @@protoc_insertion_point(class_scope:tareaRPC.Inbox)
  })
_sym_db.RegisterMessage(Inbox)

Usuario = _reflection.GeneratedProtocolMessageType('Usuario', (_message.Message,), {
  'DESCRIPTOR' : _USUARIO,
  '__module__' : 'tarea2_pb2'
  # @@protoc_insertion_point(class_scope:tareaRPC.Usuario)
  })
_sym_db.RegisterMessage(Usuario)

Destined_Message = _reflection.GeneratedProtocolMessageType('Destined_Message', (_message.Message,), {
  'DESCRIPTOR' : _DESTINED_MESSAGE,
  '__module__' : 'tarea2_pb2'
  # @@protoc_insertion_point(class_scope:tareaRPC.Destined_Message)
  })
_sym_db.RegisterMessage(Destined_Message)

Confirmation = _reflection.GeneratedProtocolMessageType('Confirmation', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMATION,
  '__module__' : 'tarea2_pb2'
  # @@protoc_insertion_point(class_scope:tareaRPC.Confirmation)
  })
_sym_db.RegisterMessage(Confirmation)


DESCRIPTOR._options = None

_TAREARPC = _descriptor.ServiceDescriptor(
  name='TareaRPC',
  full_name='tareaRPC.TareaRPC',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=179,
  serialized_end=486,
  methods=[
  _descriptor.MethodDescriptor(
    name='Read_Message',
    full_name='tareaRPC.TareaRPC.Read_Message',
    index=0,
    containing_service=None,
    input_type=_USUARIO,
    output_type=_INBOX,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='actualizar_usuarios',
    full_name='tareaRPC.TareaRPC.actualizar_usuarios',
    index=1,
    containing_service=None,
    input_type=_USUARIO,
    output_type=_CONFIRMATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Send_Message',
    full_name='tareaRPC.TareaRPC.Send_Message',
    index=2,
    containing_service=None,
    input_type=_DESTINED_MESSAGE,
    output_type=_CONFIRMATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='See_users',
    full_name='tareaRPC.TareaRPC.See_users',
    index=3,
    containing_service=None,
    input_type=_USUARIO,
    output_type=_INBOX,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='See_messages',
    full_name='tareaRPC.TareaRPC.See_messages',
    index=4,
    containing_service=None,
    input_type=_USUARIO,
    output_type=_INBOX,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TAREARPC)

DESCRIPTOR.services_by_name['TareaRPC'] = _TAREARPC

# @@protoc_insertion_point(module_scope)
